/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-08-26 07:35:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_002dmetro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.6.RELEASE.jar", Long.valueOf(1589695319161L));
    _jspx_dependants.put("jar:file:/C:/Back%20Up%20Labs/Sunny/Workspaces/STS-WS2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PurplePebbles/WEB-INF/lib/spring-webmvc-5.2.6.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1588041852000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.3.2.RELEASE.jar", Long.valueOf(1590506081595L));
    _jspx_dependants.put("jar:file:/C:/Back%20Up%20Labs/Sunny/Workspaces/STS-WS2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PurplePebbles/WEB-INF/lib/spring-security-taglibs-5.3.2.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1588774120000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fdata_002drole_005fdata_002don_002dvalidate_002dform_005fdata_002don_002derror_002dform_005fdata_002dclear_002dinvalid_005fclass_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fdata_002drole_005fdata_002don_002dvalidate_002dform_005fdata_002don_002derror_002dform_005fdata_002dclear_002dinvalid_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fdata_002drole_005fdata_002don_002dvalidate_002dform_005fdata_002don_002derror_002dform_005fdata_002dclear_002dinvalid_005fclass_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\t\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<title>My App - Login Form</title>\r\n");
      out.write("<!-- Metro 4 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"https://cdn.metroui.org.ua/v4.3.2/css/metro-all.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".login-form {\r\n");
      out.write("\t\twidth: 350px;\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\ttop: 50%;\r\n");
      out.write("\t\tmargin-top: -160px;\r\n");
      out.write("\t\tbackground-color: #EEE6F2\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"h-vh-100 bg-white\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"../../metro/js/metro.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tfunction invalidForm() {\r\n");
      out.write("\t\t\t\tvar form = $(this);\r\n");
      out.write("\t\t\t\tform.addClass(\"ani-ring\");\r\n");
      out.write("\t\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\t\tform.removeClass(\"ani-ring\");\r\n");
      out.write("\t\t\t\t}, 1000);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction validateForm() {\r\n");
      out.write("\t\t\t\t$(\".login-form\").animate({\r\n");
      out.write("\t\t\t\t\topacity : 0\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Metro 4 -->\r\n");
      out.write("\t\t<script src=\"https://cdn.metroui.org.ua/v4.3.2/js/metro.min.js\"></script>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fdata_002drole_005fdata_002don_002dvalidate_002dform_005fdata_002don_002derror_002dform_005fdata_002dclear_002dinvalid_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/view/login-metro.jsp(29,2) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/authenticateUser", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/view/login-metro.jsp(29,2) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("POST");
      // /WEB-INF/view/login-metro.jsp(29,2) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "login-form  p-6 mx-auto border bd-default win-shadow");
      // /WEB-INF/view/login-metro.jsp(29,2) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "data-role", "validator");
      // /WEB-INF/view/login-metro.jsp(29,2) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "data-clear-invalid", "2000");
      // /WEB-INF/view/login-metro.jsp(29,2) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "data-on-error-form", "invalidForm");
      // /WEB-INF/view/login-metro.jsp(29,2) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "data-on-validate-form", "validateForm");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<span class=\"mif-vpn-lock mif-4x place-right fg-mauve\"\r\n");
            out.write("\t\t\t\t\t\tstyle=\"margin-top: -10px;\"></span>\r\n");
            out.write("\t\t\t\t<h2 class=\"text-light\">Login to app</h2>\r\n");
            out.write("\t\t\t\t<hr class=\"thin mt-4 mb-4 bg-white\">\r\n");
            out.write("\t\t\t\t<div class=\"form-group\">\r\n");
            out.write("\t\t\t\t\t\t<input type=\"text\" data-role=\"input\" name=\"username\"\r\n");
            out.write("\t\t\t\t\t\t\t\tplaceholder=\"username\" data-prepend=\"<span class='mif-user'>\">\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t<div class=\"form-group\">\r\n");
            out.write("\t\t\t\t\t\t<input type=\"password\" data-role=\"input\" name=\"password\"\r\n");
            out.write("\t\t\t\t\t\t\t\tdata-prepend=\"<span class='mif-key'>\"\r\n");
            out.write("\t\t\t\t\t\t\t\tplaceholder=\"Enter your password...\"\r\n");
            out.write("\t\t\t\t\t\t\t\tdata-validate=\"required minlength=6\">\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t<div class=\"form-group mt-10\">\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<button class=\"button\"\r\n");
            out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: #C3A6F7; color: black\">Logon</button>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<a\r\n");
            out.write("\t\t\t\t\t\t\t\thref=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/register/showRegistrationForm\"\r\n");
            out.write("\t\t\t\t\t\t\t\tclass=\"button\" role=\"button\" aria-pressed=\"true\"\r\n");
            out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: #E7D2F1; color: black\"> Register\r\n");
            out.write("\t\t\t\t\t\t\t\tNew User </a>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fdata_002drole_005fdata_002don_002dvalidate_002dform_005fdata_002don_002derror_002dform_005fdata_002dclear_002dinvalid_005fclass_005faction.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }
}
