package scriptsengine.reportsengine.interfaces;

import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import scriptsengine.uploadengine.exceptions.EX_General;

/**
 * 
 * XLS Report Generator Interface
 */
public interface IXLSReportGenerator
{
	/**
	 * In case a Report is to be generated in a new WorkBook
	 * 
	 * @param filePath
	 *             - Work Book File Folder location
	 * @param srvObj
	 *             - Report Srvice Invocation object Instance
	 * @throws EX_General
	 */
	public void triggerXLSReportGeneration(String filePath, Object srvObj) throws EX_General;

	/**
	 * In case a Report is to be generated by adding a sheet to existing workbook context
	 * 
	 * @param wbctxt
	 *             - Existing Workbook Context
	 * @param srvObj
	 *             - Report Srvice Invocation object Instance
	 * 
	 * @throws EX_General
	 */
	public void triggerXLSReportGeneration(XSSFWorkbook wbctxt, Object srvObj) throws EX_General;

	/**
	 * Perform basic checks on the Service Object
	 * 
	 * @param srvObj
	 *             - Report Srvice Invocation object Instance
	 * @throws EX_General
	 */
	public void performBasicChecks(Object srvObj) throws EX_General;

}
